### ISSUE TITLE
Simple docker image not working after #9

### ISSUE THREAD

**Issue by kriscarle** [mapbox/sentinel-tiler#10]
Got the error `A defined coordinate reference system is required` which appears to be a rasterio error. After rebuilding with the custom image it works fine. 

Sorry haven't investigated past that, just thought I'd drop a note here in case anyone else hits this while upgrading.

**Comment by vincentsarago** [comment]
Thanks @kriscarle, I'm going to investigate today

**Comment by vincentsarago** [comment]
should be fixed now.
Problem was that by default there was ` GDAL_DATA: /var/task/share/gdal` set in the lambda runtime. We have to remove this when using rasterio wheels.

I've refactored the whole thing and it should be easier now.

so either to `make wheel & make deploy-wheel` or `make custom & make deploy-custom`
