### ISSUE TITLE
Histogram Parameters

### ISSUE THREAD

**Issue by wmaiouiru** [mapbox/sentinel-tiler#11]
In histo: `-` delimited rgb histogram min/max (default: 0,16000-0,16000-0,16000 )

It seems like parameter 1, 2, 3 corresponds to RGB. But what does the parameter 0 do? Modifying doesn't seem to do anything. When you supply a single number, does it specify the max? 

code url: 
https://github.com/mapbox/sentinel-tiler/blame/master/README.md#L133

**Comment by vincentsarago** [comment]
`0,16000` should define `min` and `max` to use to rescale for 0 to 255. 

in the `app` we need `min, max` for each band https://github.com/mapbox/sentinel-tiler/blob/9f02d044bfd8535ee6bc6a4bec71fb22b11f825e/app/sentinel.py#L96-L102

so `0,16000-0,16000-0,16000` as url parameter will be translated to 
((0, 16000), (0, 16000), (0, 16000)) in https://github.com/mapbox/sentinel-tiler/blob/9f02d044bfd8535ee6bc6a4bec71fb22b11f825e/app/sentinel.py#L84

**Comment by wmaiouiru** [comment]
aw, I see I was not reading the sentence correctly - delimited rgb histogram
I thought the convention was comma[,] delimited such as the following:
0-16000,0-16000,0-16000
