### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/sentinel-tiler#8]
I am hitting CORS issue that is very similar to the one described for the [landast-tiler](https://github.com/mapbox/landsat-tiler/issues/9). However, this time setting a AWS_REGION  variable doesn't seem to fix the problem.

After digging around a little in the serverless issues (e.g. [#4681](https://github.com/serverless/serverless/issues/4681))  it seems that *maybe* we need to define Access-Control-Allow-* headers ?

> If you want to use CORS with the lambda-proxy integration, remember to include the Access-Control-Allow-* headers in your headers object

As defined in the serverless [docs](https://serverless.com/framework/docs/providers/aws/events/apigateway/#enabling-cors)

Here is a screenshot of how it looks on the frontend:
![sentinel2_cors_blocked](https://user-images.githubusercontent.com/16657983/37965874-86b778b0-31be-11e8-8bf3-87d1441ca795.png)

**Comment by vincentsarago** [comment]
I think this happened with the new serverless release, can you confirm which version of serverless you are using ? 
I may need to update https://github.com/vincentsarago/lambda-proxy which is handling the api-gateway integration.

**Comment by samsammurphy** [comment]
```
$ sls --version
1.26.0
```
I am going to try and play with this again over the weekend to see if I didn't miss something.

**Comment by samsammurphy** [comment]
One idea might be to add the following line

`"Access-Control-Allow-Credentials" : true // Required for cookies, authorization headers with HTTPS`

to [here](https://github.com/vincentsarago/lambda-proxy/blob/0b2d6903757f2a1fae6deb7ad426713e47782b68/lambda_proxy/proxy.py#L207) perhaps? 

I am not at all familiar with lambda proxies though, so that is a bit of a guess. Again, will try testing over the wkd.

**Comment by vincentsarago** [comment]
@samsammurphy I can't reproduce this but with sls `1.26.1` (event with `Access-Control-Allow-Credentials` set or not) is your endpoint still up and running ?

**Comment by samsammurphy** [comment]
I had removed it.. new endpoint up

`const sentinel_tiler_url = 'https://r1jzg3qt9c.execute-api.eu-central-1.amazonaws.com/dev'`

there is no CORS error, but it still is hitting something.. hopefully will find more info to help diagnose..

**Comment by samsammurphy** [comment]
In the initScene() function there is a query for metadata on [line 91](https://github.com/mapbox/sentinel-tiler/blob/cd69d4d62d2abd8ce36a0531d4b732823d136672/viewer/js/app.js#L91).

Here is an example of one of my query urls:
`https://r1jzg3qt9c.execute-api.eu-central-1.amazonaws.com/dev/sentinel/metadata/S2B_tile_20180303_17SMD_0?'pmim=5&pmax=95`

here is part of a response from jquery .fail() when trying to $.getJSON such a query:
```
responseJSON: Object { errorMessage: "A defined coordinate reference system is required" }
responseText: "{\"errorMessage\": \"A defined coordinate reference system is required\"}"
setRequestHeader: function setRequestHeader()
state: function state()
status: 500
statusCode: function statusCode()
statusText: "Internal Server Error"
```

As you see the error message is "A defined coordinate reference system is required". I'm not sure why that error is raised. Any ideas?

**Comment by Dharnidharka** [comment]
@samsammurphy I am running into the same issue "A defined coordinate reference system is required". Have you been able to figure out the cause? landsat-tiler works normally though.

**Comment by vincentsarago** [comment]
are you using the `simple` or `custom` build ? 
if you are using the `simple` you need to remove https://github.com/mapbox/sentinel-tiler/blob/master/serverless.yml#L18 
cc @samsammurphy @Dharnidharka

**Comment by Dharnidharka** [comment]
@vincentsarago I am using the simple build. I'll make the suggested fix and get back to you. Thank you.

**Comment by Dharnidharka** [comment]
@vincentsarago Removing the line has resolved the issue. Thanks a lot.

**Comment by vincentsarago** [comment]
no problem @Dharnidharka, btw just checked your web, seems you are doing great stuff, love to see what you'll do with sentinel-tiler :-)  

sorry @samsammurphy I should have realized that 21 days ago 🤦‍♂️,

Feel free to close here if it also worked for you

**Comment by Dharnidharka** [comment]
@vincentsarago Thank you. I recently started exploring satellite imagery and this tool is simply awesome. Will let you know if I manage to do something worthwhile on top of it :)

**Comment by samsammurphy** [comment]
:tada: that worked. thanks @vincentsarago !
